version: '3.9'

services:
  mysql:
    image: mysql:8.2.0
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/init/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: daas
      MYSQL_USER: user
      MYSQL_PASSWORD: pass